### ISSUE TITLE
Request for License Change from GPL-3.0 to More Permissive License

### ISSUE THREAD

**Issue by audi0615** [adafruit/Adafruit_NeoMatrix#28]
Hi.

Could you please change the current GPL-3.0 license of your library to a more permissive license like MIT or BSD. 

Thanks.

**Comment by dhalbert** [comment]
Note that the license is LGPL-3.0, not GPL-3.0. LGPL does not require disclosing the rest of your source code. It has other requirements which are "Lesser". The requirements for an embedded product are subject to interpretation and I'm not going to interpret them at the moment.

The original commit that chose that license is here: https://github.com/adafruit/Adafruit_NeoMatrix/commit/d6f2bb3f57f0479c558b66aeea140161c2acc278. Note that https://github.com/adafruit/Adafruit_NeoPixel is also LGPL, perhaps because it was based on previous LGPL code.

@ladyada Do you remember why these are LGPL?

**Comment by audi0615** [comment]
Thanks for your clarification. However, the license specified in GitHub is still GPL-3.0. Could you please revise it to be LGPL-3.0?

<img width="843" alt="image" src="https://github.com/user-attachments/assets/161b6f21-08f0-4e62-9923-82b80db7e257">

**Comment by dhalbert** [comment]
Thanks for pointing that out. The license selector for GitHub does not include LGPL-3.0 as an easy choice. However, it appears that adding `COPYING.LESSER` will fix that.
https://github.com/licensee/licensee/issues/143
https://github.com/github/choosealicense.com/issues/607
The GitHub assistance on this is kind of a mess right now!

**Comment by dhalbert** [comment]
I merged #29, and now it says this:

![image](https://github.com/user-attachments/assets/3bc203cc-7250-4c26-af13-b7b71bc31c9e)

Note that LGPL-3.0 is an addendum to GPL-3.0. It is not a standalone license. I can also add SPDX lines to the source code, but the source code already says LGPL, not GPL. Is this OK for you now? I'll continue to inquire about why LGPL was chosen as the original license.

**Comment by audi0615** [comment]
Thank you for your prompt action and for informing me that LGPL-3.0 is an addendum. 
Now everything is very clear.

**Comment by ladyada** [comment]
ok do i have to do anything or is this resolved? :D

**Comment by dhalbert** [comment]
All set, thanks!
